project:
  type: book
  output-dir: ../docs

book:
  title: "rtemislive"
  author: "E.D. Gennatas"
  date: "03/29/2023"
  favicon: favicon.ico
  # google-analytics: "UA-127457544-1"
  sidebar:
    style: "floating"
    logo: "rtemislive_logo.png"
    title: " "
    tools:
      - icon: github
        href: https://github.com/egenn/rtemislivedocs
  chapters:
   - index.qmd
   - Introduction.qmd
   - Data.qmd
   - Preproc.qmd
   - Describe.qmd
   - Plot.qmd
   - Heat.qmd
   - Graph.qmd
   - Cluster.qmd
   - Decom.qmd
   - massGLM.qmd
   - Predict.qmd
   - MRview.qmd
   - Protein.qmd
   - PDB.qmd
  page-footer: "&copy; 2023 E.D. Gennatas"

bibliography: references.bib

format:
  html:
    theme:
      light: rtemis-light.scss
      dark: rtemis-dark.scss
    css: bootstrap.lambdamd.css
    highlight-style: atom-one
